name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\").ok' --quiet"
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install jq
      run: sudo apt-get install -y jq
    
    - name: Create .env file
      run: |
        echo "PORT=5000" > .env
        echo "MONGODB_URI=mongodb://localhost:27017/food-review-test" >> .env
        echo "NODE_ENV=test" >> .env
    
    - name: Start the server
      run: npm run dev &
      env:
        PORT: 5000
        MONGODB_URI: mongodb://localhost:27017/food-review-test
        NODE_ENV: test
    
    - name: Wait for server to start
      run: |
        for i in {1..30}; do
          if curl -s http://localhost:5000/api/v1/foods > /dev/null; then
            echo "Server is up!"
            exit 0
          fi
          echo "Waiting for server to start... ($i/30)"
          sleep 1
        done
        echo "Server failed to start"
        exit 1
    
    - name: Run API tests
      run: |
        chmod +x test-api.sh
        ./test-api.sh
      env:
        PORT: 5000
        MONGODB_URI: mongodb://localhost:27017/food-review-test
        NODE_ENV: test 